products_loc = '.product-item'
product_prices_loc = '//span[contains(@id, "product-price")]'
product_names_loc = '.product-item-name'
sort_select_loc = '#sorter'
sorter_action_loc = '.sorter-action'
grid_btn_loc = '//*[@data-value="grid"]'
list_btn_loc = '//*[@data-value="list"]'
